services:
  web:
    image: developersota/frontend:${ENV:-dev}
    container_name: web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV:-dev}
