name: Deploy App

on:
  push:
    branches:
      - dev # Chạy pipeline khi có push lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Bước 3: Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Bước 4: Build và Push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/novel-fe:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/novel-fe:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Bước 1: SSH vào VPS và deploy Docker Compose
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /novel
            docker-compose down web
            docker-compose pull web
            docker-compose up -d web
